use_frameworks!

target 'ZText_Example' do
  pod 'ZText', :path => '../'

  target 'ZText_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
    pod 'FBSnapshotTestCase', :git => 'https://github.com/facebook/ios-snapshot-test-case', :tag => '2.1.1'
    pod 'Nimble-Snapshots'
  end
end
